// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOM7wfyVdRZf-SXqyr3zMHkxySqvLv1WQ',
    appId: '1:1016560329130:web:c277b026d0d037470f4bd3',
    messagingSenderId: '1016560329130',
    projectId: 'proyectoflutter-d14a3',
    authDomain: 'proyectoflutter-d14a3.firebaseapp.com',
    storageBucket: 'proyectoflutter-d14a3.appspot.com',
    measurementId: 'G-KJ5BY5QG0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLQbee8D7IsZeYa-o5QBBDrAx9P6e2oA',
    appId: '1:1016560329130:android:942bd0c700538e1b0f4bd3',
    messagingSenderId: '1016560329130',
    projectId: 'proyectoflutter-d14a3',
    storageBucket: 'proyectoflutter-d14a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSo8X7tANH9h9dtk1EhQvsQlxSVjvJVyU',
    appId: '1:1016560329130:ios:33b27e3e479111e40f4bd3',
    messagingSenderId: '1016560329130',
    projectId: 'proyectoflutter-d14a3',
    storageBucket: 'proyectoflutter-d14a3.appspot.com',
    iosClientId: '1016560329130-i88eo9ms4ri3i69evuup6qedf9vnc7cg.apps.googleusercontent.com',
    iosBundleId: 'com.ReyFer.proyectoflutter',
  );
}
